project_id = "susniyygjqxfvisjwpun"

[functions.setup-demo-users]
verify_jwt = false

[functions.send-admin-invite]
verify_jwt = false

[functions.send-announcement]
verify_jwt = false

[functions.send-team-invite]
verify_jwt = false

[functions.send-shift-notifications]
verify_jwt = false

[functions.send-event-notifications]
verify_jwt = false

[functions.forward-n8n-meeting]
verify_jwt = false

[functions.generate-meeting-summary]
verify_jwt = false
